// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzijjdoostqbsvkzdklg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6aWpqZG9vc3RxYnN2a3pka2xnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MTcwNDEsImV4cCI6MjA1ODI5MzA0MX0.Fb9r6eoFpTwf-AAiPqHHC0ZJFffuhbo-bdrFOYwbNeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);